title: TheVibeTales
author: Geeta Sneha
email: thevibetales@gmail.com
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  As I juggle through life, here stay my daily experiences, thoughts and a few stories along with memories.

# social links
twitter_username: geeta_sneha # DO NOT include the @ character, or else the build will fail!
github_username:  geetcodes # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
